package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Servo;
import frc.robot.OI;


public class Elevator extends Subsystem {

    private OI interf = new OI();
    private Spark elevatorSpeedController9;
    private Servo ratchetShifter;
    private int servoAngle = 90;
    private long startTime = 1;

    public Elevator() {
        elevatorSpeedController9 = new Spark(6);
        addChild("Elevator Speed Controller 9",elevatorSpeedController9);
        elevatorSpeedController9.setInverted(false);  // SWITCH THIS TO TRUE TO SWITCH ELEVATOR DIRECTION
                
        ratchetShifter = new Servo(8);
        addChild("Ratchet Shifter",ratchetShifter);
    }

    @Override
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    // Called every tick
    @Override
    public void periodic() {

        // Raises the elevator when "Y (yellow)" is pressed and held
        // Lowers the elevator when "A (green)" is pressed and held
        // Stops the elevator when neither is pressed and held
        
        if (interf.joystick1.getRawButtonPressed(4)){
            servoAngle = 180;
            ratchetShifter.setAngle(servoAngle); 
            elevatorSpeedController9.set(-.75);
            startTime = System.currentTimeMillis();
            return;
        }
        else if (System.currentTimeMillis() - startTime < 100){
            return;
        }

        if (interf.joystick1.getRawButton(4)){
            elevatorSpeedController9.set(.75);
            servoAngle = 180;
        }
        else if (interf.joystick1.getRawButton(2)){
            elevatorSpeedController9.set(-.75);
            servoAngle = 90;
        }
        else {
            elevatorSpeedController9.set(0);
        }
        ratchetShifter.setAngle(servoAngle); 

        // Put code here to be run every loop
    }
}

