package frc.robot.subsystems;


import frc.robot.commands.*;
import frc.robot.OI;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;


public class Elevator extends Subsystem {

    public OI interf = new OI();
    private Spark elevatorSpeedController9;

    public Elevator() {
        elevatorSpeedController9 = new Spark(6);
        addChild("Elevator Speed Controller 9",elevatorSpeedController9);
        elevatorSpeedController9.setInverted(false);
    }

    @Override
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        interf.joystick1.getRawButtonPressed(4);
        interf.joystick1.getRawButtonPressed(2);

        // Put code here to be run every loop
    }
}

